server:
    port : 8080

services:
    article:
        url: http://localhost:8083
    comment:
        url: http://localhost:8082
    user:
        url: http://localhost:8084

keycloak:
    realm: blog
    auth-server-url: http://localhost:8081/auth
    resource: article-service
    bearer-only: true
    principal-attribute: preferred_username
