services:
    article:
        url: http://article-service:8080
    comment:
        url: http://comment-service:8080
    user:
        url: http://user-service:8080

keycloak:
    realm: blog
    auth-server-url: ${SSO_ADDRESS}
    resource: gateway-service
    bearer-only: true
    principal-attribute: preferred_username
    credentials:
        secret: ${SSO_SECRET}
