spring:
    application:
        name: gateway-service

logging.level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.keycloak: TRACE

management:
    endpoint:
        health:
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: prometheus, health
    metrics:
        tags:
            application: ${spring.application.name}