services:
    article:
        url: http://localhost:8079/article-service
    comment:
        url: http://localhost:8079/comment-service
    user:
        url: http://localhost:8079/user-service

keycloak:
    realm: blog
    auth-server-url: http://localhost:8079/auth
    resource: gateway-service